//! 模拟数据 —— 字段命名贴近 legado / React 范例。

#[derive(Clone, Debug)]
pub struct Book {
    pub id: String,
    pub title: String,
    pub author: String,
    pub kind: Kind,
    pub origin: String, // 网络书源名 或 本地路径
    pub group: String,
    pub category: String,
    pub status: String, // 连载 / 完结
    pub words: String,
    pub total: u32,
    pub read: u32, // 0-based chapter index
    pub latest: String,
    pub last_read: String,
    pub new_count: u32,
    pub intro: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    Local,
    Network,
}

#[derive(Clone, Debug)]
pub struct Source {
    pub id: String,
    pub name: String,
    pub group: String,
    pub url: String,
    pub enabled: bool,
    pub explore: bool,
    pub respond_ms: i32, // -1 = 超时
    pub categories: Vec<String>,
}

pub fn shelf() -> Vec<Book> {
    vec![
        Book {
            id: "b1".into(),
            title: "诡秘之主".into(),
            author: "爱潜水的乌贼".into(),
            kind: Kind::Network,
            origin: "起点中文网".into(),
            group: "完结".into(),
            category: "玄幻".into(),
            status: "完结".into(),
            words: "446.5万".into(),
            total: 1432,
            read: 812,
            latest: "第1432章 新的征程".into(),
            last_read: "10分钟前".into(),
            new_count: 0,
            intro: "蒸汽与机械的浪潮中，谁能触及非凡？历史和黑暗的迷雾里，又是谁在耳语？".into(),
        },
        Book {
            id: "b2".into(),
            title: "道诡异仙".into(),
            author: "狐尾的笔".into(),
            kind: Kind::Network,
            origin: "起点中文网".into(),
            group: "追更".into(),
            category: "仙侠".into(),
            status: "连载".into(),
            words: "312.8万".into(),
            total: 1068,
            read: 1062,
            latest: "第1068章 心素".into(),
            last_read: "2小时前".into(),
            new_count: 6,
            intro: "诡异的天道，异常的仙佛，是真？是假？陷入迷惘的李火旺无法分辨。".into(),
        },
        Book {
            id: "b3".into(),
            title: "大奉打更人".into(),
            author: "卖报小郎君".into(),
            kind: Kind::Network,
            origin: "番茄小说".into(),
            group: "完结".into(),
            category: "仙侠".into(),
            status: "完结".into(),
            words: "380.2万".into(),
            total: 1284,
            read: 355,
            latest: "第1284章 大结局".into(),
            last_read: "昨天 22:14".into(),
            new_count: 0,
            intro: "这个世界，有儒；有道；有佛；有妖；有术士。".into(),
        },
        Book {
            id: "b4".into(),
            title: "深空彼岸".into(),
            author: "辰东".into(),
            kind: Kind::Network,
            origin: "笔趣阁①".into(),
            group: "追更".into(),
            category: "科幻".into(),
            status: "连载".into(),
            words: "402.1万".into(),
            total: 1520,
            read: 1498,
            latest: "第1520章 彼岸花开".into(),
            last_read: "3天前".into(),
            new_count: 22,
            intro: "浩瀚的宇宙中，一片星系的生灭，也不过是刹那的斑驳流光。".into(),
        },
        Book {
            id: "b5".into(),
            title: "凡人修仙传".into(),
            author: "忘语".into(),
            kind: Kind::Network,
            origin: "纵横中文网".into(),
            group: "经典".into(),
            category: "仙侠".into(),
            status: "完结".into(),
            words: "771.6万".into(),
            total: 2446,
            read: 2446,
            latest: "第2446章 飞升仙界".into(),
            last_read: "上周".into(),
            new_count: 0,
            intro: "一个普通山村小子，偶然下进入到当地江湖小门派。".into(),
        },
        Book {
            id: "b6".into(),
            title: "我在精神病院学斩神".into(),
            author: "三九音域".into(),
            kind: Kind::Network,
            origin: "番茄小说".into(),
            group: "追更".into(),
            category: "都市".into(),
            status: "连载".into(),
            words: "298.4万".into(),
            total: 1356,
            read: 901,
            latest: "第1356章 天庭".into(),
            last_read: "5天前".into(),
            new_count: 3,
            intro: "你是否想过，在霓虹璀璨的都市之下，潜藏着来自古老神话的怪物？".into(),
        },
        Book {
            id: "b7".into(),
            title: "三体".into(),
            author: "刘慈欣".into(),
            kind: Kind::Local,
            origin: "~/Books/三体全集.epub".into(),
            group: "经典".into(),
            category: "科幻".into(),
            status: "完结".into(),
            words: "88.0万".into(),
            total: 104,
            read: 37,
            latest: "第104章 尾声".into(),
            last_read: "1小时前".into(),
            new_count: 0,
            intro: "文化大革命如火如荼进行的同时，军方探寻外星文明的绝秘计划取得了突破。".into(),
        },
        Book {
            id: "b8".into(),
            title: "活着".into(),
            author: "余华".into(),
            kind: Kind::Local,
            origin: "~/Books/活着.txt".into(),
            group: "经典".into(),
            category: "文学".into(),
            status: "完结".into(),
            words: "12.1万".into(),
            total: 12,
            read: 12,
            latest: "第12章 老人与牛".into(),
            last_read: "上个月".into(),
            new_count: 0,
            intro: "讲述了一个人历尽世间沧桑和磨难的一生。".into(),
        },
        Book {
            id: "b9".into(),
            title: "百年孤独".into(),
            author: "加西亚·马尔克斯".into(),
            kind: Kind::Local,
            origin: "~/Books/百年孤独.epub".into(),
            group: "经典".into(),
            category: "文学".into(),
            status: "完结".into(),
            words: "25.3万".into(),
            total: 20,
            read: 4,
            latest: "第20章".into(),
            last_read: "2周前".into(),
            new_count: 0,
            intro: "多年以后，面对行刑队，奥雷里亚诺·布恩迪亚上校将会回想起……".into(),
        },
        Book {
            id: "b10".into(),
            title: "围城".into(),
            author: "钱锺书".into(),
            kind: Kind::Local,
            origin: "~/Books/围城.txt".into(),
            group: "经典".into(),
            category: "文学".into(),
            status: "完结".into(),
            words: "23.0万".into(),
            total: 9,
            read: 0,
            latest: "第9章".into(),
            last_read: "未读".into(),
            new_count: 0,
            intro: "城外的人想冲进去，城里的人想逃出来。".into(),
        },
    ]
}

pub fn sources() -> Vec<Source> {
    vec![
        Source {
            id: "s1".into(),
            name: "起点中文网".into(),
            group: "正版".into(),
            url: "https://www.qidian.com".into(),
            enabled: true,
            explore: true,
            respond_ms: 212,
            categories: vec![
                "玄幻".into(),
                "奇幻".into(),
                "仙侠".into(),
                "都市".into(),
                "历史".into(),
                "科幻".into(),
                "悬疑".into(),
            ],
        },
        Source {
            id: "s2".into(),
            name: "番茄小说".into(),
            group: "正版".into(),
            url: "https://fanqienovel.com".into(),
            enabled: true,
            explore: true,
            respond_ms: 188,
            categories: vec![
                "男频热榜".into(),
                "女频热榜".into(),
                "新书榜".into(),
                "完结榜".into(),
                "巅峰榜".into(),
            ],
        },
        Source {
            id: "s3".into(),
            name: "笔趣阁①".into(),
            group: "聚合".into(),
            url: "https://www.biquge.example".into(),
            enabled: true,
            explore: true,
            respond_ms: 540,
            categories: vec![
                "玄幻魔法".into(),
                "武侠修真".into(),
                "都市言情".into(),
                "历史军事".into(),
                "排行榜".into(),
            ],
        },
        Source {
            id: "s4".into(),
            name: "纵横中文网".into(),
            group: "正版".into(),
            url: "https://www.zongheng.com".into(),
            enabled: true,
            explore: true,
            respond_ms: 301,
            categories: vec![
                "月票榜".into(),
                "畅销榜".into(),
                "新书榜".into(),
                "完本".into(),
            ],
        },
        Source {
            id: "s5".into(),
            name: "晋江文学城".into(),
            group: "正版".into(),
            url: "https://www.jjwxc.net".into(),
            enabled: true,
            explore: true,
            respond_ms: 422,
            categories: vec![
                "言情".into(),
                "纯爱".into(),
                "衍生".into(),
                "无CP".into(),
                "完结金榜".into(),
            ],
        },
        Source {
            id: "s6".into(),
            name: "七猫小说".into(),
            group: "正版".into(),
            url: "https://www.qimao.com".into(),
            enabled: true,
            explore: false,
            respond_ms: 260,
            categories: vec![],
        },
        Source {
            id: "s7".into(),
            name: "69书吧".into(),
            group: "聚合".into(),
            url: "https://www.69shu.example".into(),
            enabled: false,
            explore: true,
            respond_ms: 690,
            categories: vec!["全部".into(), "排行".into()],
        },
        Source {
            id: "s8".into(),
            name: "书海阁".into(),
            group: "聚合".into(),
            url: "https://www.shuhai.example".into(),
            enabled: false,
            explore: false,
            respond_ms: -1,
            categories: vec![],
        },
    ]
}

/// 发现页的假数据（按 seed 稳定生成）
pub fn discover_books(source_name: &str, cat: &str) -> Vec<Book> {
    const POOL: &[(&str, &str, &str)] = &[
        ("剑来", "烽火戏诸侯", "仙侠"),
        ("雪中悍刀行", "烽火戏诸侯", "武侠"),
        ("庆余年", "猫腻", "历史"),
        ("将夜", "猫腻", "玄幻"),
        ("赤心巡天", "情何以甚", "仙侠"),
        ("灵境行者", "卖报小郎君", "都市"),
        ("宿命之环", "爱潜水的乌贼", "奇幻"),
        ("夜的命名术", "会说话的肘子", "都市"),
        ("十日终焉", "杀虫队队员", "悬疑"),
        ("光阴之外", "耳根", "仙侠"),
        ("神秘复苏", "佛前献花", "悬疑"),
        ("学霸的黑科技系统", "晨星LL", "科幻"),
        ("临高启明", "吹牛者", "历史"),
        ("全职高手", "蝴蝶蓝", "网游"),
        ("遮天", "辰东", "玄幻"),
        ("长安的荔枝", "马伯庸", "历史"),
        ("星门", "老鹰吃小鸡", "都市"),
        ("黎明之剑", "远瞳", "奇幻"),
    ];
    let seed = source_name.len() * 17 + cat.len() * 31;
    let n = 9 + (seed % 5);
    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let (title, author, category) = POOL[(seed + i * 7) % POOL.len()];
        if out.iter().any(|b: &Book| b.title == title) {
            continue;
        }
        let total = 300 + ((seed + i * 13) % 2200) as u32;
        let done = (seed + i).is_multiple_of(3);
        out.push(Book {
            id: title.to_owned(), // 演示书池标题唯一，避免不同书籍共用 ID。
            title: title.to_owned(),
            author: author.to_owned(),
            kind: Kind::Network,
            origin: "—".into(), // 绘制时用 source_name 覆盖显示
            group: "未分组".into(),
            category: category.to_owned(),
            status: if done { "完结" } else { "连载" }.into(),
            words: "—".into(),
            total,
            read: 0,
            latest: "最新章节".into(),
            last_read: "未读".into(),
            new_count: 0,
            intro: "发现页示例简介。".into(),
        });
    }
    // origin 无法改 &'static，绘制时单独显示 source_name
    let _ = source_name;
    out
}
